The following modules were not unloaded:
  (Use "module --force purge" to unload all):

  1) 2023.01   2) StdEnv
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: numpy in /home1/s4950836/.local/lib/python3.11/site-packages (from -r requirements.txt (line 1)) (1.26.4)
Requirement already satisfied: scipy in /home1/s4950836/.local/lib/python3.11/site-packages (from -r requirements.txt (line 2)) (1.13.0)
Requirement already satisfied: molmass in /home1/s4950836/.local/lib/python3.11/site-packages (from -r requirements.txt (line 3)) (2024.5.24)
Requirement already satisfied: prodimopy in /home1/s4950836/.local/lib/python3.11/site-packages (from -r requirements.txt (line 4)) (2.3.2)
Requirement already satisfied: tqdm in /home1/s4950836/.local/lib/python3.11/site-packages (from -r requirements.txt (line 5)) (4.66.4)
ERROR: Could not find a version that satisfies the requirement itertools (from versions: none)
ERROR: No matching distribution found for itertools

[notice] A new release of pip is available: 24.0 -> 25.0.1
[notice] To update, run: pip install --upgrade pip
srun: error: node16: task 0: Exited with exit code 1
srun: Terminating StepId=15618474.0
Generating permutations
Generating dataset
Loading permutations from dataset_permutations.h5...
Total permutations to process: 1
Using 16 CPU cores.
  0%|          | 0/1 [00:00<?, ?it/s]  0%|          | 0/1 [00:05<?, ?it/s]
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/cvmfs/hpc.rug.nl/versions/2023.01/rocky8/x86_64/amd/zen3/software/Python/3.11.5-GCCcore-13.2.0/lib/python3.11/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
                    ^^^^^^^^^^^^^^^^^^^
  File "/home1/s4950836/mockSpectra/dataCube.py", line 177, in _process_permutation
    slab.generate_spectrum(verbose=False)
  File "/home1/s4950836/mockSpectra/slabModel.py", line 77, in generate_spectrum
    mol.generateSlab(dens, temp, channel["wl"], channel["wu"], cache_folder=self.cache_folder)
  File "/home1/s4950836/mockSpectra/molecule.py", line 63, in generateSlab
    self.data = runs.run_0D_slab(Ng    = column_density,            # The gas column density in molecules per cm2
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/s4950836/.local/lib/python3.11/site-packages/prodimopy/run_slab.py", line 273, in run_0D_slab
    I_nu_line,tau_ret,I_nu,tau_lbl,pop_l,pop_u = run_0D_point(Ng,Tg,vturb,molecule,mol_mass,nu_0,Aul,E_u,E_l,gu,gl,QTpath,isotopolog,nu_grid,mode)
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/s4950836/.local/lib/python3.11/site-packages/prodimopy/run_slab.py", line 337, in run_0D_point
    pop_u = boltzmann_distribution(E_u,gu[:,:,0],Tg,fetch_QT(molecule,isotopolog[0],Tg,QTpath)).reshape(1,N_lines,1)
                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/s4950836/.local/lib/python3.11/site-packages/prodimopy/run_slab.py", line 184, in fetch_QT
    if(T<1.):
       ^^^^
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home1/s4950836/mockSpectra/my_datacube.py", line 93, in <module>
    datacube.gen_dataset(
  File "/home1/s4950836/mockSpectra/dataCube.py", line 141, in gen_dataset
    for _ in pool.imap_unordered(process_permutation_partial, permutation_keys):
  File "/cvmfs/hpc.rug.nl/versions/2023.01/rocky8/x86_64/amd/zen3/software/Python/3.11.5-GCCcore-13.2.0/lib/python3.11/multiprocessing/pool.py", line 873, in next
    raise value
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
srun: error: node16: task 0: Exited with exit code 1
srun: Terminating StepId=15618474.1

###############################################################################
H치br칩k Cluster
Job 15618474 for user s4950836
Finished at: Thu Mar 13 13:02:53 CET 2025

Job details:
============

Job ID                         : 15618474
Name                           : datacube-generator
User                           : s4950836
Partition                      : regularmedium
Nodes                          : node16
Number of Nodes                : 1
Cores                          : 16
Number of Tasks                : 1
State                          : FAILED  
Submit                         : 2025-03-13T10:01:17
Start                          : 2025-03-13T13:02:29
End                            : 2025-03-13T13:02:49
Reserved walltime              : 2-12:00:00
Used walltime                  :   00:00:20
Used CPU time                  :   00:00:13 (Efficiency:  4.12%)
% User (Computation)           : 75.62%
% System (I/O)                 : 24.38%
Total memory reserved          : 514542M
Maximum memory used            : 0.00 

Acknowledgements:
=================

Please see this page for information about acknowledging H치br칩k in your publications:

https://wiki.hpc.rug.nl/habrok/introduction/scientific_output

################################################################################
